### ISSUE TITLE
why is it ! and not /

### ISSUE THREAD

**Issue by kwlou** [thomasloesch/diceDiscordBot#3]
i dont want to use my underdeveloped pinky to press shift and make a !roll ok.

/roll 1d20 makes random number between 1-20

**Comment by thomasloesch** [comment]
I will see if I can support both options.

**Comment by thomasloesch** [comment]
After a cursory review of this functionality at work, I'm not sure it can be supported with the libraries I'm using. I will look into more, but I am using [this](https://github.com/Discord4J-Addons/Commands4J) and I'm not sure how to change the !

**Comment by thomasloesch** [comment]
Simple change actually. Turns out the initial character can be anything! Went ahead and changed it to /.
