### ISSUE TITLE
rolling multiple dice types breaks the algorithm

### ISSUE THREAD

**Issue by kwlou** [thomasloesch/diceDiscordBot#4]
!roll 1d20  1d4 produces a number greater than 100
It should produce randn 1-20 and randn 1-4

**Comment by thomasloesch** [comment]
The root cause of this issue is actually quite simple.

It seems that the input is being concatenated improperly after being received by the bot.
In the example given above, the bot changes 1d20 1d4 to 1d201d4. This means that the boss tries rolling 1d201 instead of the requested roll.
